{"name": "test_mult[4-8-30]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 32 == 30\n  +32\n  -30", "trace": "self = <testcases.test_func.Test_Pytest object at 0x10700fa20>\nfixture_func = <pyCode.calc.Calculator object at 0x10700fbe0>, a = 4, b = 8\nresult = 30\n\n    @pytest.mark.parametrize('a,b,result', test_data[2])\n    @allure.feature('乘法测试')\n    def test_mult(self, fixture_func, a, b, result):\n>       assert fixture_func.mult(a, b) == result\nE       assert 32 == 30\nE         +32\nE         -30\n\ntest_func.py:38: AssertionError"}, "parameters": [{"name": "a", "value": "4"}, {"name": "b", "value": "8"}, {"name": "result", "value": "30"}], "start": 1594611737356, "stop": 1594611737357, "uuid": "7bb76959-2a9b-4ca6-bbad-56ed2b7f442d", "historyId": "56844e06e015eacf8bbb7d6cef1d87e5", "testCaseId": "f23b8f69bb19ec69f89b4ceb1ecccfec", "fullName": "testcases.test_func.Test_Pytest#test_mult", "labels": [{"name": "feature", "value": "乘法测试"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_func"}, {"name": "subSuite", "value": "Test_Pytest"}, {"name": "host", "value": "bogon"}, {"name": "thread", "value": "56802-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_func"}]}