{"name": "test_add[4-8-9]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 12 == 9\n +  where 12 = <bound method Calculator.add of <pyCode.calc.Calculator object at 0x107068e48>>(4, 8)\n +    where <bound method Calculator.add of <pyCode.calc.Calculator object at 0x107068e48>> = <pyCode.calc.Calculator object at 0x107068e48>.add", "trace": "self = <testcases.test_func.Test_Pytest object at 0x1070689e8>, cal_demo = <pyCode.calc.Calculator object at 0x107068e48>, a = 4, b = 8, result = 9\n\n    @pytest.mark.parametrize('a,b,result', [(1, 1, 2), (2, 2, 4), (4, 8, 9)])\n    def test_add(self, cal_demo, a, b, result):\n>       assert cal_demo.add(a, b) == result\nE       assert 12 == 9\nE        +  where 12 = <bound method Calculator.add of <pyCode.calc.Calculator object at 0x107068e48>>(4, 8)\nE        +    where <bound method Calculator.add of <pyCode.calc.Calculator object at 0x107068e48>> = <pyCode.calc.Calculator object at 0x107068e48>.add\n\ntestcases/test_func.py:8: AssertionError"}, "attachments": [{"name": "stdout", "source": "1711719e-e1c8-4478-b549-b94fa2dbc052-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "4"}, {"name": "b", "value": "8"}, {"name": "result", "value": "9"}], "start": 1594353369349, "stop": 1594353369350, "uuid": "c1929f73-cf0e-4f53-9cb5-c4265110d48d", "historyId": "8cc8578512410beb269300d7f1700470", "testCaseId": "9954af4c850efe74843731f91ac39489", "fullName": "testcases.test_func.Test_Pytest#test_add", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_func"}, {"name": "subSuite", "value": "Test_Pytest"}, {"name": "host", "value": "bogon"}, {"name": "thread", "value": "46427-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_func"}]}